add wave -noupdate -expand -group {test_clause_array_top} /test_clause_array_top/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} /test_clause_array_top/test_clause_array/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} /test_clause_array_top/test_clause_array/clause_array/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} /test_clause_array_top/test_clause_array/clause_array/clause8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_0/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_0/clause2_1/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_0/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {terminal_cell} /test_clause_array_top/test_clause_array/clause_array/clause8/clause4_1/clause2_1/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {max_in_4_datas_inst0} /test_clause_array_top/test_clause_array/clause_array/max_in_4_datas_inst0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {max_in_4_datas_inst0} -group {max_in_2_datas_inst0} /test_clause_array_top/test_clause_array/clause_array/max_in_4_datas_inst0/max_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_clause_array_top} -expand -group {test_clause_array} -expand -group {clause_array} -group {max_in_4_datas_inst0} -group {max_in_2_datas_inst1} /test_clause_array_top/test_clause_array/clause_array/max_in_4_datas_inst0/max_in_2_datas_inst1/*
