add wave -noupdate -expand -group {test_bin_manager_top} /test_bin_manager_top/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} /test_bin_manager_top/test_bin_manager/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} /test_bin_manager_top/test_bin_manager/bin_manager/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {ctrl_bm} /test_bin_manager_top/test_bin_manager/bin_manager/ctrl_bm/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {rd_bin_info} /test_bin_manager_top/test_bin_manager/bin_manager/rd_bin_info/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {find_global_bkt_lvl} /test_bin_manager_top/test_bin_manager/bin_manager/find_global_bkt_lvl/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {bkt_across_bin} /test_bin_manager_top/test_bin_manager/bin_manager/bkt_across_bin/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst0} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst1} /test_bin_manager_top/test_bin_manager/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {bram_vars_bins_inst} /test_bin_manager_top/test_bin_manager/bin_manager/bram_vars_bins_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {bram_clauses_bins_inst} /test_bin_manager_top/test_bin_manager/bin_manager/bram_clauses_bins_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {bram_global_var_state_inst} /test_bin_manager_top/test_bin_manager/bin_manager/bram_global_var_state_inst/*
add wave -noupdate -expand -group {test_bin_manager_top} -expand -group {test_bin_manager} -expand -group {bin_manager} -group {bram_global_lvl_state_inst} /test_bin_manager_top/test_bin_manager/bin_manager/bram_global_lvl_state_inst/*
