add wave -noupdate -expand -group {test_sat_bin_top} /test_sat_bin_top/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} /test_sat_bin_top/test_sat_bin/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} /test_sat_bin_top/test_sat_bin/sat_bin/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {ctrl_bm} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/ctrl_bm/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {rd_bin_info} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/rd_bin_info/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_vs_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_vs_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst0} -group {scatter_to_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst0/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {load_bin} -group {scatter_to_ls_inst} -group {scatter_to_4_datas_inst1} -group {scatter_to_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/load_bin/scatter_to_ls_inst/scatter_to_4_datas_inst1/scatter_to_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {find_global_bkt_lvl} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/find_global_bkt_lvl/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {bkt_across_bin} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/bkt_across_bin/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_vs_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_vs_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst0} -group {reduce_in_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst0/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {update_bin} -group {reduce_ls_inst} -group {reduce_in_4_datas_inst1} -group {reduce_in_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/update_bin/reduce_ls_inst/reduce_in_4_datas_inst1/reduce_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {bram_vars_bins_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/bram_vars_bins_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {bram_clauses_bins_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/bram_clauses_bins_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {bram_global_var_state_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/bram_global_var_state_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {bin_manager} -group {bram_global_lvl_state_inst} /test_sat_bin_top/test_sat_bin/sat_bin/bin_manager/bram_global_lvl_state_inst/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {ctrl_core} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/ctrl_core/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} -group {var_state2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/var_state2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} -group {var_state2_0} -group {var_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/var_state2_0/var_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} -group {var_state2_0} -group {var_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/var_state2_0/var_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} -group {var_state2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/var_state2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} -group {var_state2_1} -group {var_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/var_state2_1/var_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_0} -group {var_state2_1} -group {var_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_0/var_state2_1/var_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} -group {var_state2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/var_state2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} -group {var_state2_0} -group {var_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/var_state2_0/var_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} -group {var_state2_0} -group {var_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/var_state2_0/var_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} -group {var_state2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/var_state2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} -group {var_state2_1} -group {var_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/var_state2_1/var_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {var_state8} -group {var_state4_1} -group {var_state2_1} -group {var_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/var_state8/var_state4_1/var_state2_1/var_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} -group {lvl_state2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/lvl_state2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} -group {lvl_state2_0} -group {lvl_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/lvl_state2_0/lvl_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} -group {lvl_state2_0} -group {lvl_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/lvl_state2_0/lvl_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} -group {lvl_state2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/lvl_state2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} -group {lvl_state2_1} -group {lvl_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/lvl_state2_1/lvl_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_0} -group {lvl_state2_1} -group {lvl_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_0/lvl_state2_1/lvl_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} -group {lvl_state2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/lvl_state2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} -group {lvl_state2_0} -group {lvl_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/lvl_state2_0/lvl_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} -group {lvl_state2_0} -group {lvl_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/lvl_state2_0/lvl_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} -group {lvl_state2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/lvl_state2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} -group {lvl_state2_1} -group {lvl_state1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/lvl_state2_1/lvl_state1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {lvl_state8} -group {lvl_state4_1} -group {lvl_state2_1} -group {lvl_state1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/lvl_state8/lvl_state4_1/lvl_state2_1/lvl_state1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} -group {dcd_in_var2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/dcd_in_var2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} -group {dcd_in_var2_0} -group {dcd_in_var1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/dcd_in_var2_0/dcd_in_var1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} -group {dcd_in_var2_0} -group {dcd_in_var1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/dcd_in_var2_0/dcd_in_var1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} -group {dcd_in_var2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/dcd_in_var2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} -group {dcd_in_var2_1} -group {dcd_in_var1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/dcd_in_var2_1/dcd_in_var1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_0} -group {dcd_in_var2_1} -group {dcd_in_var1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_0/dcd_in_var2_1/dcd_in_var1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} -group {dcd_in_var2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/dcd_in_var2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} -group {dcd_in_var2_0} -group {dcd_in_var1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/dcd_in_var2_0/dcd_in_var1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} -group {dcd_in_var2_0} -group {dcd_in_var1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/dcd_in_var2_0/dcd_in_var1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} -group {dcd_in_var2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/dcd_in_var2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} -group {dcd_in_var2_1} -group {dcd_in_var1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/dcd_in_var2_1/dcd_in_var1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {state_list} -group {decision} -group {dcd_in_var8} -group {dcd_in_var4_1} -group {dcd_in_var2_1} -group {dcd_in_var1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/state_list/decision/dcd_in_var8/dcd_in_var4_1/dcd_in_var2_1/dcd_in_var1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_0} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_0/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_0} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_0/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_0} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_0/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {terminal_cell} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/terminal_cell/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_0} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_0/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_0} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_0/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {clause8} -group {clause4_1} -group {clause2_1} -group {clause1_1} -group {lit8} -group {lit4_1} -group {lit2_1} -group {lit1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/clause8/clause4_1/clause2_1/clause1_1/lit8/lit4_1/lit2_1/lit1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {max_in_4_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/max_in_4_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {max_in_4_datas_inst0} -group {max_in_2_datas_inst0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/max_in_4_datas_inst0/max_in_2_datas_inst0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {clause_array} -group {max_in_4_datas_inst0} -group {max_in_2_datas_inst1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/clause_array/max_in_4_datas_inst0/max_in_2_datas_inst1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} -group {c_len2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/c_len2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} -group {c_len2_0} -group {c_len1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/c_len2_0/c_len1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} -group {c_len2_0} -group {c_len1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/c_len2_0/c_len1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} -group {c_len2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/c_len2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} -group {c_len2_1} -group {c_len1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/c_len2_1/c_len1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_0} -group {c_len2_1} -group {c_len1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_0/c_len2_1/c_len1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} -group {c_len2_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/c_len2_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} -group {c_len2_0} -group {c_len1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/c_len2_0/c_len1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} -group {c_len2_0} -group {c_len1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/c_len2_0/c_len1_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} -group {c_len2_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/c_len2_1/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} -group {c_len2_1} -group {c_len1_0} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/c_len2_1/c_len1_0/*
add wave -noupdate -expand -group {test_sat_bin_top} -expand -group {test_sat_bin} -expand -group {sat_bin} -group {sat_engine} -group {c_len8} -group {c_len4_1} -group {c_len2_1} -group {c_len1_1} /test_sat_bin_top/test_sat_bin/sat_bin/sat_engine/c_len8/c_len4_1/c_len2_1/c_len1_1/*
